"""
Constants for the Budget Management Application.
"""

# Budget natures
NATURE_FONCTIONNEMENT = "Fonctionnement"
NATURE_INVESTISSEMENT = "Investissement"
NATURES_BUDGET = [NATURE_FONCTIONNEMENT, NATURE_INVESTISSEMENT]

# Bon de commande types
TYPE_BC_ASSISTANCE = "Assistance"
TYPE_BC_FORMATION = "Formation"
TYPE_BC_PRESTATION = "Prestation"
TYPE_BC_MATERIEL = "Matériel"
TYPE_BC_LICENCES = "Licences"
TYPES_BC = [TYPE_BC_ASSISTANCE, TYPE_BC_FORMATION, TYPE_BC_PRESTATION, TYPE_BC_MATERIEL, TYPE_BC_LICENCES]

# Project investment types
TYPE_INV_MATERIEL = "Matériel"
TYPE_INV_LICENCE = "Licence"
TYPE_INV_INSTALLATION = "Installation"
TYPE_INV_FORMATION = "Formation"
TYPE_INV_ACCOMPAGNEMENT = "Accompagnement"
TYPES_INVESTISSEMENT = [TYPE_INV_MATERIEL, TYPE_INV_LICENCE, TYPE_INV_INSTALLATION, TYPE_INV_FORMATION, TYPE_INV_ACCOMPAGNEMENT]

# Contract statuses
STATUT_ACTIF = "Actif"
STATUT_EXPIRE = "Expiré"
STATUT_RESILIE = "Résilié"
STATUTS_CONTRAT = [STATUT_ACTIF, STATUT_EXPIRE, STATUT_RESILIE]

# Project statuses
STATUT_PROJET_EN_COURS = "En cours"
STATUT_PROJET_TERMINE = "Terminé"
STATUT_PROJET_SUSPENDU = "Suspendu"
STATUTS_PROJET = [STATUT_PROJET_EN_COURS, STATUT_PROJET_TERMINE, STATUT_PROJET_SUSPENDU]

# Todo priorities
PRIORITE_BASSE = "Basse"
PRIORITE_NORMALE = "Normale"
PRIORITE_HAUTE = "Haute"
PRIORITE_URGENTE = "Urgente"
PRIORITES_TODO = [PRIORITE_BASSE, PRIORITE_NORMALE, PRIORITE_HAUTE, PRIORITE_URGENTE]

# Priority colors
PRIORITY_COLORS = {
    PRIORITE_BASSE: "#4ecdc4",
    PRIORITE_NORMALE: "#0d7377",
    PRIORITE_HAUTE: "#ffa500",
    PRIORITE_URGENTE: "#ff6b6b"
}

# UI Colors
COLOR_PRIMARY = "#0d7377"
COLOR_SUCCESS = "#4ecdc4"
COLOR_DANGER = "#ff6b6b"
COLOR_WARNING = "#ffa500"
COLOR_BG_DARK = "#0a0a0a"
COLOR_BG_CARD = "#1a1a1a"

# Date format
DATE_FORMAT = "%Y-%m-%d"
DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"
